Improve coverage
fedora-infra/mirrors-countme pull request #55
Opened 2023-05-29 12:34 UTC by LenkaSeg

2023-06-01 14:51 UTC, nphilipp requested changes
Please review my suggestion and if applicable, squash the commits and merge. Thanks!

2023-06-01 14:51 UTC, nphilipp commented on tests/test_integrate.py
> +        assert len(csv_dump.readlines()) > 0
The second call to `totals()` also writes the sqlite DB, so both can be rolled into one:

```
        csv_dump = open(f"{tmp_dir}/test.csv", "w+")
        totals(
            countme_totals=totalsdb,
            countme_raw=rawdb,
            progress=False,
            csv_dump=csv_dump,
        )
        db = sqlite3.connect(totalsdb)
        rows_no = db.execute("select count(*) from countme_totals;").fetchone()[0]
        assert int(rows_no) > 0
        csv_dump.seek(0)
        assert len(csv_dump.readlines()) > 0
```

I'll commit this into your branch.

2023-06-02 09:57 UTC, LenkaSeg commented
Done, thanks!

2023-06-02 11:51 UTC, nphilipp approved these changes
Please review my suggestion and if applicable, squash the commits and merge. Thanks!

2023-06-02 11:52 UTC, merged